### ISSUE TITLE
cstruct version constraint < 4.0.0

### ISSUE THREAD

**Issue by ursetto** [mirage/ocaml-qcow#114]
It seems this package won't compile with cstruct >= 4.0.0, I'm assuming due to the sexplib change documented at https://github.com/mirage/ocaml-cstruct/releases/tag/v4.0.0. Installing dependencies into a local switch using the .opam that comes with the project got me cstruct 5.0.0, and caused the rather unhelpful message `Unbound module Sexplib` when trying to build. 

`opam install qcow` downgraded cstruct to 3.7.0 and fixed this issue, because cstruct is constrained to < 4.0.0 on opam, but not in the .opam file included with the project.

I'm thinking this constraint should be propagated to `qcow.opam` as well.

**Comment by hannesm** [comment]
thanks for your report, this has been fixed in #123
